name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do Código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build do JAR
      - name: Build Lambda Function
        run: mvn clean package

      # Configurar AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Upload do JAR e Layer para S3
      - name: Upload to S3
        run: |
          aws s3 cp target/lambda-function.jar s3://${{ secrets.S3_BUCKET_NAME }}/lambda-function.jar
          aws s3 cp terraform/layers/ffmpeg-layer.zip s3://${{ secrets.S3_BUCKET_NAME }}/ffmpeg-layer.zip

      # Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Validate Terraform
        run: terraform -chdir=terraform validate

      - name: Plan Terraform
        run: terraform -chdir=terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform -chdir=terraform apply -auto-approve tfplan
